#\u516C\u5171\u914D\u7F6E\u4E0Eprofiles\u9009\u62E9\u65E0\u5173
#mybatis:
 # typeAliasesPackage: sjjd.mei.equi.pojo
 # mapperLocations: classpath:mappers/*.xml


#\u5F00\u53D1\u914D\u7F6E
server:  
  tomcat:
    max-http-post-size: -1
spring:
 #datasource:
  # url: jdbc:mysql://localhost:3306/sjjd_cxhosp?useUnicode=true&characterEncoding=utf-8
  # username: root
   #password: 123456
   #driver-class-name: com.mysql.jdbc.Driver

 redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 100
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 50
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    lettuce:
      pool:
        max-active: 100
        max-idle: 50
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    password: ''
    port: 6379




  